version: "3.5"

services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m 'elephant season wise pyramid jaguar number away trap skirt guilt capital reveal' --networkId '101010' --allowUnlimitedContractSize --noVMErrorsOnRPCResponse
    ports:
      - 8545:8545

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_ROOT_DATABASE: root-db
    volumes:
      - ./ops/db:/docker-entrypoint-initdb.d:ro
      - mongo:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27117:27017

  webapp:
    container_name: webapp
    image: blockchain_app:latest
    environment:
      - CI=true
    ports:
      -8080:8080

volumes:
  mongo:
