version: "3.9"
services:
  mongo-baseline:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_DATABASE: root-db
    volumes:
      - mongo:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27017:27017

  baseline:
    build:
      context: .
      dockerfile: packages/baseline/Dockerfile
    depends_on:
      - mongo-baseline
    command: yarn start

  postgres-api:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      APP_DB_USER: "${APP_DB_USER}"
      APP_DB_PASS: "${APP_DB_PASS}"
      APP_DB_NAME: "${APP_DB_NAME}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./ops/db:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data/

  nats:
    image: nats
    ports:
      - "${NATS_PORT}:4222"
volumes:
  mongo:
  pgdata:
