export declare const getStatus: (req: any, res: any) => Promise<void>;
export declare const getCommits: (req: any, res: any) => Promise<void>;
export declare const getCommit: (req: any, res: any) => Promise<void>;
export declare const createCommit: (req: any, res: any) => Promise<void>;
export declare const sendCommitToPartners: (req: any, res: any) => Promise<void>;
export declare const sendCommitMainnet: (req: any, res: any) => Promise<void>;
export declare const getMerkleTrees: (req: any, res: any) => Promise<void>;
export declare const getMerkleTree: (req: any, res: any) => Promise<void>;
export declare const createMerkleTree: (req: any, res: any) => Promise<void>;
export declare const deleteMerkleTree: (req: any, res: any) => Promise<void>;
export declare const deleteAllMerkleTrees: (req: any, res: any) => Promise<void>;
export declare const getContracts: (req: any, res: any) => Promise<void>;
export declare const deleteAllContracts: (req: any, res: any) => Promise<void>;
export declare const getSettings: (req: any, res: any) => Promise<void>;
export declare const saveSettings: (req: any, res: any, next: any) => Promise<void>;
//# sourceMappingURL=rest-methods.d.ts.map