version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt update && sudo apt install nodejs npm -y && npm install -g yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build all packages
          command: yarn build
      - run:
          name: Run all CI tests
          command: yarn lerna run test
