version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build all packages
          command: yarn build
      - run:
          name: Run all CI tests
          command: yarn lerna run test
