version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  build_test:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Build Main
          command: yarn build
      - run:
          name: Build Packages
          command: yarn build:packages
      - run: 
          name: Run all CI tests
          command: yarn run test:ci
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
  test_my_app:
    jobs:
      - build_test