version: "2.1"
orbs:
  node: circleci/node@4.2.0
jobs:
  build_test:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Packages
          command: yarn lerna run build
      - run:
          name: Build Main
          command: yarn build
      - run:
          name: Run all CI tests
          command: yarn lerna run test
workflows:
  test_my_app:
    jobs:
      - build_test
