version: "3.8"
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
    volumes:
      - ./ops/ganache_health.sh:/app/health-check.sh:delegated
    healthcheck:
      test: ["CMD", "sh", "health-check.sh"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_DATABASE: root-db
    volumes:
      - mongo:/data/db
    logging:
      options:
        max-size: 10m
    ports:
      - 27017:27017

  baseline:
    build:
      context: ../../.
      dockerfile: packages/baseline/Dockerfile
    profiles: ["production"]
    depends_on:
      - mongo
      - ganache
    environment:
      NODE_ENV: production
    command: yarn start

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    profiles: ["development"]
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo:
