version: "3.8"
services:
  ganache:
    command: ganache-cli -m "elephant season wise pyramid jaguar number away trap skirt guilt capital reveal" --networkId 101010 --allowUnlimitedContractSize --noVMErrorsOnRPCResponse
